# Generated by ./ip-to-dns.sh
resource "aws_route53_record" "training-vm-oz-0" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-0.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.85.100"]
}

resource "aws_route53_record" "training-vm-oz-1" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-1.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.87.180"]
}

resource "aws_route53_record" "training-vm-oz-2" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-2.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.84.179"]
}

resource "aws_route53_record" "training-vm-oz-3" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-3.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["118.138.235.117"]
}

resource "aws_route53_record" "training-vm-oz-4" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-4.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.87.56"]
}

resource "aws_route53_record" "training-vm-oz-5" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-5.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.86.89"]
}

resource "aws_route53_record" "training-vm-oz-6" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-6.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.84.215"]
}

resource "aws_route53_record" "training-vm-oz-7" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-7.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.86.231"]
}

resource "aws_route53_record" "training-vm-oz-8" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-8.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.84.172"]
}

resource "aws_route53_record" "training-vm-oz-9" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-9.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.85.33"]
}

resource "aws_route53_record" "training-vm-oz-10" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-10.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["118.138.233.83"]
}

resource "aws_route53_record" "training-vm-oz-11" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-11.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.86.205"]
}

resource "aws_route53_record" "training-vm-oz-12" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-12.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.86.208"]
}

resource "aws_route53_record" "training-vm-oz-13" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-13.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.85.215"]
}

resource "aws_route53_record" "training-vm-oz-14" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-14.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.86.152"]
}

resource "aws_route53_record" "training-vm-oz-15" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-15.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.84.210"]
}

resource "aws_route53_record" "training-vm-oz-16" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-16.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.85.210"]
}

resource "aws_route53_record" "training-vm-oz-17" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-17.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.85.23"]
}

resource "aws_route53_record" "training-vm-oz-18" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-18.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["118.138.237.119"]
}

resource "aws_route53_record" "training-vm-oz-19" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-19.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.87.68"]
}

resource "aws_route53_record" "training-vm-oz-20" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-20.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.85.30"]
}

resource "aws_route53_record" "training-vm-oz-21" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-21.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.87.15"]
}

resource "aws_route53_record" "training-vm-oz-22" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-22.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.84.125"]
}

resource "aws_route53_record" "training-vm-oz-23" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-23.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.86.87"]
}

resource "aws_route53_record" "training-vm-oz-24" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-24.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.86.245"]
}

resource "aws_route53_record" "training-vm-oz-25" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-25.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.84.197"]
}

resource "aws_route53_record" "training-vm-oz-26" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-26.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["118.138.236.18"]
}

resource "aws_route53_record" "training-vm-oz-27" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-27.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.85.218"]
}

resource "aws_route53_record" "training-vm-oz-28" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-28.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.86.94"]
}

resource "aws_route53_record" "training-vm-oz-29" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-29.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.86.156"]
}

resource "aws_route53_record" "training-vm-oz-30" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-30.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.87.235"]
}

resource "aws_route53_record" "training-vm-oz-31" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-31.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.87.11"]
}

resource "aws_route53_record" "training-vm-oz-32" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-32.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.85.136"]
}

resource "aws_route53_record" "training-vm-oz-33" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-33.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.87.207"]
}

resource "aws_route53_record" "training-vm-oz-34" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-34.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["118.138.236.73"]
}

resource "aws_route53_record" "training-vm-oz-35" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-35.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["118.138.238.44"]
}

resource "aws_route53_record" "training-vm-oz-36" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-36.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.86.149"]
}

resource "aws_route53_record" "training-vm-oz-37" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-37.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.87.191"]
}

resource "aws_route53_record" "training-vm-oz-38" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-38.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.84.60"]
}

resource "aws_route53_record" "training-vm-oz-39" {
  zone_id = data.aws_route53_zone.training-gxp-eu.zone_id
  name    = "gat-39.oz.training.galaxyproject.eu"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.86.85"]
}

