# Generated by ./ip-to-dns.sh
resource "aws_route53_record" "training-vm-us-0" {
  zone_id = var.training-gxp-us
  name    = "gat-0.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.154.146"]
}
resource "aws_route53_record" "training-vm-us-0-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-0.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-0.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-1" {
  zone_id = var.training-gxp-us
  name    = "gat-1.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.155.5"]
}
resource "aws_route53_record" "training-vm-us-1-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-1.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-1.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-2" {
  zone_id = var.training-gxp-us
  name    = "gat-2.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.153.230"]
}
resource "aws_route53_record" "training-vm-us-2-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-2.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-2.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-3" {
  zone_id = var.training-gxp-us
  name    = "gat-3.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.152.252"]
}
resource "aws_route53_record" "training-vm-us-3-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-3.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-3.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-4" {
  zone_id = var.training-gxp-us
  name    = "gat-4.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.154.48"]
}
resource "aws_route53_record" "training-vm-us-4-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-4.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-4.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-5" {
  zone_id = var.training-gxp-us
  name    = "gat-5.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.152.239"]
}
resource "aws_route53_record" "training-vm-us-5-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-5.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-5.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-6" {
  zone_id = var.training-gxp-us
  name    = "gat-6.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.152.30"]
}
resource "aws_route53_record" "training-vm-us-6-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-6.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-6.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-7" {
  zone_id = var.training-gxp-us
  name    = "gat-7.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.155.235"]
}
resource "aws_route53_record" "training-vm-us-7-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-7.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-7.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-8" {
  zone_id = var.training-gxp-us
  name    = "gat-8.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.154.18"]
}
resource "aws_route53_record" "training-vm-us-8-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-8.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-8.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-9" {
  zone_id = var.training-gxp-us
  name    = "gat-9.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.154.248"]
}
resource "aws_route53_record" "training-vm-us-9-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-9.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-9.us.galaxy.training"]
}

