# Generated by ./ip-to-dns.sh
resource "aws_route53_record" "training-vm-us-0" {
  zone_id = var.training-gxp-us
  name    = "gat-0.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.154.146"]
}
resource "aws_route53_record" "training-vm-us-0-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-0.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-0.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-1" {
  zone_id = var.training-gxp-us
  name    = "gat-1.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.155.5"]
}
resource "aws_route53_record" "training-vm-us-1-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-1.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-1.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-2" {
  zone_id = var.training-gxp-us
  name    = "gat-2.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.153.230"]
}
resource "aws_route53_record" "training-vm-us-2-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-2.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-2.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-3" {
  zone_id = var.training-gxp-us
  name    = "gat-3.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.152.252"]
}
resource "aws_route53_record" "training-vm-us-3-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-3.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-3.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-4" {
  zone_id = var.training-gxp-us
  name    = "gat-4.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.154.48"]
}
resource "aws_route53_record" "training-vm-us-4-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-4.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-4.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-5" {
  zone_id = var.training-gxp-us
  name    = "gat-5.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.152.239"]
}
resource "aws_route53_record" "training-vm-us-5-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-5.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-5.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-6" {
  zone_id = var.training-gxp-us
  name    = "gat-6.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.152.30"]
}
resource "aws_route53_record" "training-vm-us-6-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-6.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-6.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-7" {
  zone_id = var.training-gxp-us
  name    = "gat-7.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.155.235"]
}
resource "aws_route53_record" "training-vm-us-7-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-7.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-7.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-8" {
  zone_id = var.training-gxp-us
  name    = "gat-8.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.154.18"]
}
resource "aws_route53_record" "training-vm-us-8-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-8.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-8.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-9" {
  zone_id = var.training-gxp-us
  name    = "gat-9.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.154.248"]
}
resource "aws_route53_record" "training-vm-us-9-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-9.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-9.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-10" {
  zone_id = var.training-gxp-us
  name    = "gat-10.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.155.132"]
}
resource "aws_route53_record" "training-vm-us-10-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-10.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-10.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-11" {
  zone_id = var.training-gxp-us
  name    = "gat-11.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.154.68"]
}
resource "aws_route53_record" "training-vm-us-11-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-11.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-11.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-12" {
  zone_id = var.training-gxp-us
  name    = "gat-12.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.152.31"]
}
resource "aws_route53_record" "training-vm-us-12-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-12.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-12.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-13" {
  zone_id = var.training-gxp-us
  name    = "gat-13.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.155.126"]
}
resource "aws_route53_record" "training-vm-us-13-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-13.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-13.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-14" {
  zone_id = var.training-gxp-us
  name    = "gat-14.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.152.100"]
}
resource "aws_route53_record" "training-vm-us-14-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-14.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-14.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-15" {
  zone_id = var.training-gxp-us
  name    = "gat-15.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.154.168"]
}
resource "aws_route53_record" "training-vm-us-15-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-15.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-15.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-16" {
  zone_id = var.training-gxp-us
  name    = "gat-16.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.153.148"]
}
resource "aws_route53_record" "training-vm-us-16-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-16.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-16.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-17" {
  zone_id = var.training-gxp-us
  name    = "gat-17.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.154.245"]
}
resource "aws_route53_record" "training-vm-us-17-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-17.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-17.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-18" {
  zone_id = var.training-gxp-us
  name    = "gat-18.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.154.115"]
}
resource "aws_route53_record" "training-vm-us-18-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-18.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-18.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-19" {
  zone_id = var.training-gxp-us
  name    = "gat-19.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.155.54"]
}
resource "aws_route53_record" "training-vm-us-19-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-19.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-19.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-20" {
  zone_id = var.training-gxp-us
  name    = "gat-20.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.155.11"]
}
resource "aws_route53_record" "training-vm-us-20-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-20.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-20.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-21" {
  zone_id = var.training-gxp-us
  name    = "gat-21.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.153.124"]
}
resource "aws_route53_record" "training-vm-us-21-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-21.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-21.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-22" {
  zone_id = var.training-gxp-us
  name    = "gat-22.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.154.98"]
}
resource "aws_route53_record" "training-vm-us-22-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-22.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-22.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-23" {
  zone_id = var.training-gxp-us
  name    = "gat-23.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.152.208"]
}
resource "aws_route53_record" "training-vm-us-23-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-23.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-23.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-24" {
  zone_id = var.training-gxp-us
  name    = "gat-24.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.153.135"]
}
resource "aws_route53_record" "training-vm-us-24-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-24.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-24.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-25" {
  zone_id = var.training-gxp-us
  name    = "gat-25.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.155.201"]
}
resource "aws_route53_record" "training-vm-us-25-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-25.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-25.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-26" {
  zone_id = var.training-gxp-us
  name    = "gat-26.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.153.254"]
}
resource "aws_route53_record" "training-vm-us-26-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-26.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-26.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-27" {
  zone_id = var.training-gxp-us
  name    = "gat-27.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.155.169"]
}
resource "aws_route53_record" "training-vm-us-27-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-27.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-27.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-28" {
  zone_id = var.training-gxp-us
  name    = "gat-28.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.154.54"]
}
resource "aws_route53_record" "training-vm-us-28-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-28.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-28.us.galaxy.training"]
}

resource "aws_route53_record" "training-vm-us-29" {
  zone_id = var.training-gxp-us
  name    = "gat-29.us.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["149.165.153.134"]
}
resource "aws_route53_record" "training-vm-us-29-wildcard" {
  zone_id = var.training-gxp-us
  name    = "*.interactivetoolentrypoint.interactivetool.gat-29.us.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-29.us.galaxy.training"]
}

