# Generated by ./ip-to-dns.sh
resource "aws_route53_record" "training-vm-oz-0" {
  zone_id = var.training-gxp-oz
  name    = "gat-0.oz.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.87.44"]
}
resource "aws_route53_record" "training-vm-oz-0-wildcard" {
  zone_id = var.training-gxp-oz
  name    = "*.interactivetoolentrypoint.interactivetool.gat-0.oz.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-0.oz.galaxy.training"]
}

resource "aws_route53_record" "training-vm-oz-1" {
  zone_id = var.training-gxp-oz
  name    = "gat-1.oz.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.84.201"]
}
resource "aws_route53_record" "training-vm-oz-1-wildcard" {
  zone_id = var.training-gxp-oz
  name    = "*.interactivetoolentrypoint.interactivetool.gat-1.oz.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-1.oz.galaxy.training"]
}

resource "aws_route53_record" "training-vm-oz-2" {
  zone_id = var.training-gxp-oz
  name    = "gat-2.oz.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.86.83"]
}
resource "aws_route53_record" "training-vm-oz-2-wildcard" {
  zone_id = var.training-gxp-oz
  name    = "*.interactivetoolentrypoint.interactivetool.gat-2.oz.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-2.oz.galaxy.training"]
}

resource "aws_route53_record" "training-vm-oz-3" {
  zone_id = var.training-gxp-oz
  name    = "gat-3.oz.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.85.38"]
}
resource "aws_route53_record" "training-vm-oz-3-wildcard" {
  zone_id = var.training-gxp-oz
  name    = "*.interactivetoolentrypoint.interactivetool.gat-3.oz.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-3.oz.galaxy.training"]
}

resource "aws_route53_record" "training-vm-oz-4" {
  zone_id = var.training-gxp-oz
  name    = "gat-4.oz.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.87.105"]
}
resource "aws_route53_record" "training-vm-oz-4-wildcard" {
  zone_id = var.training-gxp-oz
  name    = "*.interactivetoolentrypoint.interactivetool.gat-4.oz.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-4.oz.galaxy.training"]
}

resource "aws_route53_record" "training-vm-oz-5" {
  zone_id = var.training-gxp-oz
  name    = "gat-5.oz.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.87.224"]
}
resource "aws_route53_record" "training-vm-oz-5-wildcard" {
  zone_id = var.training-gxp-oz
  name    = "*.interactivetoolentrypoint.interactivetool.gat-5.oz.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-5.oz.galaxy.training"]
}

resource "aws_route53_record" "training-vm-oz-6" {
  zone_id = var.training-gxp-oz
  name    = "gat-6.oz.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.87.227"]
}
resource "aws_route53_record" "training-vm-oz-6-wildcard" {
  zone_id = var.training-gxp-oz
  name    = "*.interactivetoolentrypoint.interactivetool.gat-6.oz.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-6.oz.galaxy.training"]
}

resource "aws_route53_record" "training-vm-oz-7" {
  zone_id = var.training-gxp-oz
  name    = "gat-7.oz.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.87.47"]
}
resource "aws_route53_record" "training-vm-oz-7-wildcard" {
  zone_id = var.training-gxp-oz
  name    = "*.interactivetoolentrypoint.interactivetool.gat-7.oz.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-7.oz.galaxy.training"]
}

