# TODO(hexylena)
resource "aws_route53_record" "training-vm-oz-avasn" {
  zone_id = var.training-gxp-oz
  name    = "gat-avans.oz.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["145.38.206.76"]
}

# Generated by ./ip-to-dns.sh
resource "aws_route53_record" "training-vm-oz-0" {
  zone_id = var.training-gxp-oz
  name    = "gat-0.oz.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.87.166"]
}
resource "aws_route53_record" "training-vm-oz-0-wildcard" {
  zone_id = var.training-gxp-oz
  name    = "*.interactivetoolentrypoint.interactivetool.gat-0.oz.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-0.oz.galaxy.training"]
}

resource "aws_route53_record" "training-vm-oz-1" {
  zone_id = var.training-gxp-oz
  name    = "gat-1.oz.galaxy.training"
  type    = "A"
  ttl     = "7200"
  records = ["115.146.86.78"]
}
resource "aws_route53_record" "training-vm-oz-1-wildcard" {
  zone_id = var.training-gxp-oz
  name    = "*.interactivetoolentrypoint.interactivetool.gat-1.oz.galaxy.training"
  type    = "CNAME"
  ttl     = "7200"
  records = ["gat-1.oz.galaxy.training"]
}

