#!/bin/bash
# Given a list of IPs, turn them into DNS entries.
idx=${1:-0}
region=${2:-oz}

echo "# Generated by $0"
for ip in $(cat /dev/stdin); do
	cat <<-EOF
		resource "aws_route53_record" "training-vm-$region-$idx" {
		  zone_id = "\${aws_route53_zone.training-gxp-eu.zone_id}"
		  name    = "gat-${idx}.${region}.training.galaxyproject.eu"
		  type    = "A"
		  ttl     = "7200"
		  records = ["${ip}"]
		}

	EOF
	idx=$((idx + 1))
done
