#!/bin/bash
# Given a list of IPs, turn them into DNS entries.
idx=${1:-0}
region=${2:-oz}

echo "# Generated by $0"
for ip in $(cat /dev/stdin); do
	cat <<-EOF
		resource "aws_route53_record" "training-vm-$region-$idx" {
		  zone_id = var.training-gxp-$region
		  name    = "gat-${idx}.${region}.galaxy.training"
		  type    = "A"
		  ttl     = "7200"
		  records = ["${ip}"]
		}
		resource "aws_route53_record" "training-vm-$region-$idx-wildcard" {
		  zone_id = var.training-gxp-$region
		  name    = "*.interactivetoolentrypoint.interactivetool.gat-${idx}.${region}.galaxy.training"
		  type    = "CNAME"
		  ttl     = "7200"
		  records = ["gat-${idx}.${region}.galaxy.training"]
		}
		resource "aws_route53_record" "training-vm-$region-$idx-wildcard-other" {
		  zone_id = var.training-gxp-$region
		  name    = "*.gat-${idx}.${region}.galaxy.training"
		  type    = "CNAME"
		  ttl     = "7200"
		  records = ["gat-${idx}.${region}.galaxy.training"]
		}

	EOF
	idx=$((idx + 1))
done
