name: Ansible Bootstrapping

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - run: |
          ansible -a 'gat status' ${{ github.event.inputs.tags }}" -f 20 -vv > $GITHUB_STEP_SUMMARY
