name: Send to Slack

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
      - cron:  '0 * * * *'
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.4

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan
        continue-on-error: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_EU_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_EU_SECRET }}
          AWS_DEFAULT_REGION: us-east-1
          OS_AUTH_TYPE: "v3applicationcredential"
          OS_AUTH_URL: ${{ secrets.OS_VSC_AUTH_URL }}
          OS_IDENTITY_API_VERSION: "3"
          OS_REGION_NAME: "regionOne"
          OS_INTERFACE: "public"
          OS_APPLICATION_CREDENTIAL_ID: ${{ secrets.OS_VSC_APPLICATION_CREDENTIAL_ID }}
          OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.OS_VSC_APPLICATION_CREDENTIAL_SECRET }}

      - name: Update Pull Request
        uses: actions/github-script@0.9.0
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outputs.stdout }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_EU_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_EU_SECRET }}
          AWS_DEFAULT_REGION: us-east-1
          OS_AUTH_TYPE: "v3applicationcredential"
          OS_AUTH_URL: ${{ secrets.OS_BE_AUTH_URL }}
          OS_IDENTITY_API_VERSION: "3"
          OS_REGION_NAME: "regionOne"
          OS_INTERFACE: "public"
          OS_APPLICATION_CREDENTIAL_ID: ${{ secrets.OS_BE_APPLICATION_CREDENTIAL_ID }}
          OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.OS_BE_APPLICATION_CREDENTIAL_SECRET }}

      - name: Commit changed files back
        run: |
            git add .
            count=$(git diff --name-only --cached | wc -l)
            if (( count > 0 )); then
                git config --global user.email "bot@github.com"
                git config --global user.name "Github Actions"
                git commit -a -m "[slack-bot] $(date '+%H:%M')"
                git push
            fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
